---

- name: Create CASA directory
  file: path=/usr/local/bin/CASA/ state=directory mode=0755

- name: Download CASA
  get_url:
    url: https://casa.nrao.edu/download/distro/linux/release/el6/casa-release-4.7.2-el6.tar.gz
    dest: /usr/local/bin/CASA/casa-release-4.7.2-el6.tar.gz
    force: no

- name: Unarchive CASA package
  unarchive:
    src: /usr/local/bin/CASA/casa-release-4.7.2-el6.tar.gz
    dest: /usr/local/bin/CASA/
    remote_src: yes
    keep_newer: no

- name: export CASA path
  become: no
  lineinfile:
    dest: "~/.bashrc"
    line: 'export PATH=$PATH:/usr/local/bin/CASA/casa-release-4.7.2-el6/bin'
    insertafter: 'EOF'

- name: Install CASA dependencies
  yum: name="{{item}}" state=present
  with_items:
    - perl
    - libSM
    - libX11
    - libXext
    - freetype
    - libXi
    - libXrender
    - libXrandr
    - libXfixes
    - libXcursor
    - libXinerama
    - fontconfig
