# These configs are used only in development/debugging

stages:
  flux_calibration: false
  bandpass_calibration: false
  phase_calibration: false
  target_source: false

manual_flag: false
flagged:
  antennas: [1,18]

log_level: 20
#debug: 10, info: 20, warning: 30, error: 40, critical: 50

