global:
  polarizations: ['RR', 'LL']
  flux_cal_fields: &flux_cal_fields [0]
  bandpass_cal_fields: &bandpass_cal_fields [0]
  phase_cal_fields: &phase_cal_fields [1]
  target_src_field: &target_src_field [2]
  output_path: 'output'
  default_spw: "0"
  spw_range: "0"   #Example: "0,1,2,4"
  refant: 2
  target_phase_src_map: {2:[1]}

common: &common
  channel: 100
  width: 1
  minsnr: 2.0
  phase_data_column: "corrected_phase"
  angular_dispersion: &angular_dispersion
    r_threshold: 0.3
    percentage_of_min_doubtful_antennas: 20
    percentage_of_good_antennas: 70
  closure: &closure
    threshold: 17
    percentage_of_closures: 70
    percentage_of_good_triplets: 70
    percentile_threshold: 70
  detail_flagging: &detail_flagging
    time:
      sliding_window:
        start_index: 3
        bucket_size: 1
        overlap: 0
        mad_scale_factor: 3
    antenna:
      sliding_window:
        start_index: 3
        bucket_size: 10
        overlap: 5
        mad_scale_factor: 3
    baseline:
      sliding_window:
        start_index: 3
        bucket_size: 10
        overlap: 5
        mad_scale_factor: 3
    amplitude_data_column: 'corrected_amplitude'


flux_calibrator:
  <<: *common
  fields: *flux_cal_fields
  phase_data_column: "phase"

bandpass_calibrator:
  <<: *common
  fields: *bandpass_cal_fields

phase_calibrator:
  <<: *common
  fields: *phase_cal_fields
  angular_dispersion:
    <<: *angular_dispersion
    percentage_of_min_doubtful_antennas: 10

  closure:
    <<: *closure
    threshold: 35
  width: 41
  channels_to_avg: '80~120'

target_source:
  <<: *common
  fields: *target_src_field
  continuum: &continuum
    ref:
      channels_to_avg: '80~120'
      channel_width: 41
    spw:
      channels_to_avg: '80~120'
      channel_width: 41
    channel: 0
    width: 1
    self_calibration:
      minsnr: 2.0
      masking:
        threshold: '0.0'
        mask_path: ''
        bmask:
          bottom_left_corner:
            x_coordinate: 240
            y_coordinate: 240
          top_right_corner:
            x_coordinate: 270
            y_coordinate: 270
      calmode: &calmode
        p:
          loop_count : 5
          solint: '2min'
          robust: 0.5
          applymode: 'calonly'
        ap:
          loop_count : 4
          solint: '10min'
          robust: 0.5
          applymode: 'calflag'
    detail_flagging:
      <<: *detail_flagging
      amplitude_data_column: 'amplitude'


  line:
    fields: [0]
    calmode: *calmode
    continuum: *continuum