global:
    polarizations: ['RR', 'LL']
    flux_cal_field: &flux_field 0
    phase_cal_field: &phase_field 1


flux_calibration:
    field: *flux_field
    spw: 0
    channel: 100
    r_threshold: 0.3
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 0.3
    percentile_threshold: 70
    detail_falgging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
    r_flag:
      freqdevscale: 3.0
      timedevscale: 3.0
      growtime: 70.0
      growfreq: 90.0
      freqrange: '50~460'

phase_calibration:
    field: *phase_field
    spw: 0
    channel: 100
    channels_to_avg: '80~120'
    closure_threshold: 3
    percentile_threshold: 70
    detail_falgging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
    r_flag:
      freqdevscale: 3.0
      timedevscale: 3.0
      growtime: 70.0
      growfreq: 90.0

casapy:
    path: '/Applications/CASA.app/Contents/MacOS/casapy'
    model_path: '/Applications/CASA.app/Contents/data/nrao/VLA/CalModels'