global:
    polarizations: ['RR', 'LL']


flux_calibration:
    field: 0
    spw: 0
    channel: 100
    r_threshold: 0.3
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 0.3
    percentile_threshold: 70
    detail_falgging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
    r_flag:
      freqdevscale: 3.0
      timedevscale: 3.0
      growtime: 70.0
      growfreq: 90.0

phase_calibration:
    field: 1
    spw: 0
    channel: 100
    closure_threshold: 3
    percentile_threshold: 70
    detail_falgging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
    r_flag:
      freqdevscale: 3.0
      timedevscale: 3.0
      growtime: 70.0
      growfreq: 90.0

casapy:
    path: '/Applications/CASA.app/Contents/MacOS/casapy'
    model_path: '/Applications/CASA.app/Contents/data/nrao/VLA/CalModels'