global:
    polarizations: ['RR', 'LL']
    flux_cal_field: &flux_cal_field 0
    bandpass_cal_field: &bandpass_cal_field 0
    phase_cal_field: &phase_cal_field 1
    target_src_field: &target_src_field 2
    output_path: 'output'


flux_calibration:
    field: *flux_cal_field
    spw: 0
    channel: 100
    r_threshold: 0.3
    width: 1
    phase_data_column: "phase"
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 17
    percentage_of_closures: 70
    percentage_of_triplets: 70
    percentile_threshold: 70
    detail_flagging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
    casa_scripts:
      refant: 3
      minsnr: 2.0

bandpass_calibration:
    field: *bandpass_cal_field
    spw: 0
    refant: 3
    minsnr: '2.0'
    channels_to_avg: '80~120'
    r_flag:
      freqdevscale: 5.0
      timedevscale: 5.0
      growtime: 70.0
      growfreq: 90.0
      freqrange: '50~460'


phase_calibration:
    field: *phase_cal_field
    spw: 0
    channel: 100
    r_threshold: 0.3
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 35
    percentage_of_closures: 70
    percentage_of_triplets: 70
    width: 40
    phase_data_column: "corrected_phase"
    detail_flagging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 3
    r_flag:
      freqdevscale: 5.0
      timedevscale: 5.0
      growtime: 70.0
      growfreq: 90.0
    casa_scripts:
      refant: 3
      minsnr: 2.0
      channels_to_avg: '80~120'

target_source:
    field: *target_src_field
    spw: 0
    phase_data_column: "corrected_phase"
    channels_for_line: "40~480"

casapy:
    Darwin:
      path: '/Applications/CASA.app/Contents/MacOS/casapy'
      model_path: '/Applications/CASA.app/Contents/data/nrao/VLA/CalModels'
    Linux:
      path: '/usr/local/bin/CASA/casa-stable-4.7.134/bin/casa'
      model_path: '/usr/local/bin/CASA/casa-stable-4.7.134/data/nrao/VLA/CalModels'