global:
    polarizations: ['RR', 'LL']


flux_calibration:
    field: 0
    channel: 100
    r_threshold: 0.3
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 0.3
    percentile_threshold: 70