global:
    polarizations: ['RR', 'LL']
    flux_cal_fields: &flux_cal_fields [0]
    bandpass_cal_fields: &bandpass_cal_fields [0]
    phase_cal_fields: &phase_cal_fields [1]
    target_src_field: &target_src_field [2]
    output_path: 'output'
    spw: 0


flux_calibration:
    fields: *flux_cal_fields
    channel: 100
    r_threshold: 0.3
    width: 1
    phase_data_column: "phase"
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 17
    percentage_of_closures: 70
    percentage_of_triplets: 70
    percentile_threshold: 70
    detail_flagging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 4
      amplitude_data_column: 'corrected_amplitude'
    casa_scripts:
      refant: 3
      minsnr: 2.0

bandpass_calibration:
    fields: *bandpass_cal_fields
    refant: 3
    minsnr: '2.0'
    channels_to_avg: '80~120'
    r_flag:
      freqdevscale: 5.0
      timedevscale: 5.0
      growtime: 70.0
      growfreq: 90.0
      freqrange: '50~460'

phase_calibration:
    fields: *phase_cal_fields
    channel: 100
    r_threshold: 0.3
    percentage_threshold_for_min_doubtful_antennas: 30
    percentage_threshold_for_good_antenna: 70
    closure_threshold: 35
    percentage_of_closures: 70
    percentage_of_triplets: 70
    width: 40
    phase_data_column: "corrected_phase"
    detail_flagging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 3
      amplitude_data_column: 'corrected_amplitude'
    r_flag:
      freqdevscale: 5.0
      timedevscale: 5.0
      growtime: 70.0
      growfreq: 90.0
    casa_scripts:
      refant: 3
      minsnr: 2.0
      channels_to_avg: '80~120'

target_source:
    field: *target_src_field
    phase_data_column: "corrected_phase"
    continuum: &continuum
      channels_to_avg: '80~120'
      channel: 0
      width: 41
      image: &base_image
        imsize: 256
        cell: '0.5arcsec'
        robust: 0.5
        interactive: F
        niter: 100
      self_calibration:
        <<: *base_image
        solint: '2min'
        refant: 3
        minsnr: 2.0
        calmode: &calmode
          p:
            loop_count : 2
          ap:
            loop_count : 1
      detail_flagging:
        sliding_window:
          bucket_size: 10
          overlap: 5
        mad_scale_factor: 3
        amplitude_data_column: 'amplitude'

    line:
      calmode: *calmode
      continuum: *continuum
      image:
        threshold : '1000mJy'
        imsize : 256
        niter: 1
        interactive : F
        robust: 0.5
        cell: '0.5arcsec'



casapy:
    Darwin:
      path: '/Applications/CASA.app/Contents/MacOS/casapy'
      model_path: '/Applications/CASA.app/Contents/data/nrao/VLA/CalModels'
    Linux:
      path: '/usr/local/bin/CASA/casa-stable-4.7.134/bin/casa'
      model_path: '/usr/local/bin/CASA/casa-stable-4.7.134/data/nrao/VLA/CalModels'