stages:
  flag_known_bad_data: false
  flux_calibration: false
  bandpass_calibration:
    run_auto_flagging: false
    run_bandpass: false
  phase_calibration: false
  target_source:
    reference_spw:
      create_continuum: true
    all_spw:
      run_auto_flagging: false
      create_continuum: false
      create_line_image: false

known_bad_data: []

#Ex>
#known_bad_data:
#  - polarizations: ['RR', 'LL']
#    scan_ids: [1,2,3,4,5,6,7]
#    antennas: [1,18]
#
#Note: if empty array specified in polarizations, scans, or antennas, 'all' will be considered

code_profiling: false
log_level: 20
#debug: 10, info: 20, warning: 30, error: 40, critical: 50
