global:
  polarizations: ['RR', 'LL']
  flux_cal_fields: &flux_cal_fields [2]
  bandpass_cal_fields: &bandpass_cal_fields [2]
  phase_cal_fields: &phase_cal_fields [0]
  target_src_field: &target_src_field [1]
  output_path: 'src/integrationtest/output'
  spw: 0
  refant: 2

common: &common
  channel: 100
  width: 1
  minsnr: 2.0
  phase_data_column: "corrected_phase"
  angular_dispersion: &angular_dispersion
    r_threshold: 0.3
    percentage_of_min_doubtful_antennas: 20
    percentage_of_good_antennas: 70
  closure: &closure
    threshold: 17
    percentage_of_closures: 70
    percentage_of_good_triplets: 70
    percentile_threshold: 70
  detail_flagging: &detail_flagging
    sliding_window:
      bucket_size: 10
      overlap: 5
    mad_scale_factor: 3
    amplitude_data_column: 'corrected_amplitude'
  r_flag: &rflag
    freqdevscale: 5.0
    timedevscale: 5.0
    growtime: 70.0
    growfreq: 90.0


flux_calibrator:
  <<: *common
  fields: *flux_cal_fields
  phase_data_column: "phase"

bandpass_calibrator:
  <<: *common
  fields: *bandpass_cal_fields
  channels_to_avg: '80~120'
  r_flag:
    <<: *rflag
    freqrange: '50~460'

phase_calibrator:
  <<: *common
  fields: *phase_cal_fields
  angular_dispersion:
    <<: *angular_dispersion
    percentage_of_min_doubtful_antennas: 10

  closure:
    <<: *closure
    threshold: 35
  width: 40
  channels_to_avg: '80~120'

target_source:
  <<: *common
  field: *target_src_field
  continuum: &continuum
    channels_to_avg: '80~120'
    channel_width_to_avg: 41
    channel: 0
    width: 1
    image: &base_image
      imsize: 2048
      cell: '0.5arcsec'
      robust: 0.5
      clean_threshold: '2.0mJy'
      interactive: F
      niter: 100000
      cyclefactor: 4
    self_calibration:
      <<: *base_image
      minsnr: 2.0
      clean_threshold: '1.2mJy'
      masking:
        threshold: '0.0'
        mask_path: ''
      calmode: &calmode
        p:
          loop_count : 5
          solint: '2min'
          robust: 0.5
        ap:
          loop_count : 4
          solint: '10min'
          robust: 0.5
    detail_flagging:
      sliding_window:
        bucket_size: 10
        overlap: 5
      mad_scale_factor: 3
      amplitude_data_column: 'amplitude'

  line:
    calmode: *calmode
    continuum: *continuum
    image:
      threshold : '1000mJy'
      imsize : 256
      niter: 1
      interactive : F
      robust: 0.5
      cell: '0.5arcsec'

casapy:
    Darwin:
      path: '/Applications/CASA.app/Contents/MacOS/casapy'
      model_path: '/Applications/CASA.app/Contents/data/nrao/VLA/CalModels'
    Linux:
      path: '/usr/local/bin/CASA/casa-stable-4.7.134/bin/casa'
      model_path: '/usr/local/bin/CASA/casa-stable-4.7.134/data/nrao/VLA/CalModels'